[build]
publish = "_site/"
command = "bash build.sh"

[[headers]]
  for = "/rss.xml"
  [headers.values]
    Content-Type = "application/rss+xml"

# TODO: figure out how to enable webfiger redirection for Mastodon
# https://docs.joinmastodon.org/spec/webfinger/
