[build]
publish = "_site/"
command = "bash build.sh"

[[redirects]]
from = "/.well-known/webfinger*"
to = "https://mastodon.kame.moe/.well-known/webfinger:splat"
status = 301

[[headers]]
for = "/.well-known/webfinger*"
[headers.values]
Access-Control-Allow-Origin = "*"
